interface TypingTests {
  [index: number]: string;
}
export const typingTests: TypingTests = {
  1: `The history of the world is a story of conflict and cooperation, of conquest and discovery, of innovation and tradition. From the earliest civilizations to the present day, human societies have struggled to adapt to changing environments, to overcome obstacles, and to create new ways of living and governing themselves. Whether through war or diplomacy, trade or exchange, migration or settlement, humans have interacted with each other in countless ways, shaping the course of history and leaving behind a rich legacy of ideas, art, and culture.`,
  2: `The natural world is a source of wonder and beauty, a place of infinite variety and complexity. From the tiniest microbes to the largest creatures on earth, every living thing is a marvel of adaptation and evolution. The oceans, forests, deserts, and mountains are home to an incredible diversity of plants and animals, each with its own unique characteristics and behaviors. As we explore and learn about the natural world, we gain a deeper appreciation for the intricacy and interconnectedness of life on earth.`,
  3: `The human mind is a mystery that has fascinated philosophers, scientists, and artists for centuries. From the workings of memory and perception to the complexities of language and emotion, the mind is capable of remarkable feats of creativity, insight, and self-awareness. Through study and experimentation, we are beginning to unravel the secrets of the brain and unlock the potential of the human mind, leading to new discoveries and innovations in fields as diverse as psychology, neuroscience, and artificial intelligence.`,
  4: `Technology has transformed every aspect of human life, from the way we communicate and work to the way we learn and entertain ourselves. From the invention of the printing press to the development of the internet and beyond, technology has enabled us to share information, connect with others, and achieve things that were once unimaginable. As we continue to push the boundaries of what is possible, we must also consider the ethical and social implications of our technological advances, and work to ensure that they are used for the benefit of all.`,
  5: `Science is a process of discovery and exploration, a way of understanding the world around us through observation, experimentation, and analysis. From the study of atoms and molecules to the exploration of distant galaxies, science has revealed the beauty and complexity of the natural world and transformed our understanding of the universe. As we continue to investigate the mysteries of the cosmos and unravel the secrets of the smallest particles, we gain a deeper appreciation for the wonder and majesty of the universe.`,
  6: `Art is a reflection of the human experience, a way of expressing our thoughts, emotions, and ideas through creative expression. From painting and sculpture to music and dance, art has the power to inspire, provoke, and move us in ways that words alone cannot. As we engage with works of art from different cultures and traditions, we gain a deeper understanding of ourselves and the world around us, and discover new ways of seeing and interpreting the human experience.`,
  7: `The study of history is a journey of discovery, a way of understanding the past and its impact on the present. From the rise and fall of great civilizations to the struggles for freedom and equality, the study of history reveals the complexity and richness of human experience. By examining the events and people of the past, we gain a deeper understanding of the forces that shape our world today, and gain insights into the possibilities and challenges of the future.`,
};
